// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATJqmMSnZ9flMaDpzmWmQcDvRU-0Wtm60',
    appId: '1:74921815306:web:54720f8f9bec2b88b19ef3',
    messagingSenderId: '74921815306',
    projectId: 'lah-yr7am-babak',
    authDomain: 'lah-yr7am-babak.firebaseapp.com',
    storageBucket: 'lah-yr7am-babak.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzofOxH2EaNMjNoYzu1RkkkrT8wi-VUy4',
    appId: '1:74921815306:android:5069800e5470157bb19ef3',
    messagingSenderId: '74921815306',
    projectId: 'lah-yr7am-babak',
    storageBucket: 'lah-yr7am-babak.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3lPeBdQ15JvwJQdty4Dzh-9rqoo5itnM',
    appId: '1:74921815306:ios:effbdea504153514b19ef3',
    messagingSenderId: '74921815306',
    projectId: 'lah-yr7am-babak',
    storageBucket: 'lah-yr7am-babak.appspot.com',
    iosClientId: '74921815306-7vpbcqou7qg37ap8th2136nrae98pffo.apps.googleusercontent.com',
    iosBundleId: 'com.trissiane',
  );
}
